# Generated by Django 3.0.4 on 2020-05-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20200528_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='livrare_adresa',
        ),
        migrations.RemoveField(
            model_name='order',
            name='livrare_judet',
        ),
        migrations.RemoveField(
            model_name='order',
            name='livrare_localitate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
