# Generated by Django 3.0.4 on 2020-05-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200528_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='cod_postal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='judet',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='localitate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
