# Generated by Django 3.0.4 on 2020-05-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200529_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nume',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='prenume',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
